### ISSUE TITLE
trained-`Model parameters

### ISSUE THREAD

**Issue by Marwani3D** [princeton-computational-imaging/SoaP#2]
Hello,
Is there a way to download the model's pre-trained parameters?

**Comment by Ilya-Muromets** [comment]
As the code is fit per scene, trains pretty fast (it'll take like 10mins on a 4090), I left generating ouputs to the user. You can follow the two jupyter notebooks in the main repo for this.

I can also upload checkpoint files if you'd like, but I can't guarantee they'll be up to date with the main repo code or whatever the current version of `tinycudann` is.

**Comment by Ilya-Muromets** [comment]
I'll try to upload checkpoints as soon as I'm back to university and have access to my lambda machine (Early September-ish). Let me know if you need them earlier than that.

**Comment by Ilya-Muromets** [comment]
Just added a link to the trained model files in the README.md under the **Data** section; hope this helps!
