### ISSUE TITLE
"Failed to register bundle identifier" when try to setup SoaP App

### ISSUE THREAD

**Issue by arielchen07** [princeton-computational-imaging/SoaP#4]
Hi, thanks for working out such a great paper and also the app!

I was trying to setup the app on my computer. However, I got the "Failed to register bundle identifier" with me account as a personal team in the Xcode. I tried several methods mentioned online by others, but does not work.
![Screenshot 2023-11-18 at 12 36 36 PM](https://github.com/princeton-computational-imaging/SoaP/assets/105243552/7dba5dba-dbe1-480a-b8f6-48aaa6cb1ebd)
I also tried changing the Bundle Identifier name from "com.imageBundleRecorder" to "com.imageBundleRecorder.app". Then I got the error: Communication with Apple failed

I wonder if you have any idea on how to solve these problem and setup the app? Would really appreciate your help!

**Comment by arielchen07** [comment]
nvm I solved this issue by connecting my device and trust it!

**Comment by Ilya-Muromets** [comment]
Sometimes I made that error go away by changing the Bundle Identifier to something like `com.imageBundleRecorder2`, but I am very much not an iOS dev. Glad you got it running!
